### ISSUE TITLE
Add /docs folder with description and sample

### ISSUE THREAD

**Issue by davelab6** [googlefonts/zain#1]
Same as https://github.com/googlefonts/beiruti/tree/main/docs :)

**Comment by JuergenWillrodt** [comment]
Here are the files for the Docs folder
[Zain Font Family.pdf](https://github.com/googlefonts/zain/files/15280617/Zain.Font.Family.pdf)
[zain_italic_numbers.pdf](https://github.com/googlefonts/zain/files/15280618/zain_italic_numbers.pdf)
[zain_latin_numbers.pdf](https://github.com/googlefonts/zain/files/15280619/zain_latin_numbers.pdf)

**Comment by JuergenWillrodt** [comment]
[Zain.txt](https://github.com/googlefonts/zain/files/15280625/Zain.txt)
